spring:
    application:
        name: client
    profiles:
        active: okta
logging:
    level:
        root: WARN
        '[org.springframework.web]': OFF
        '[org.springframework.http]': OFF
        '[org.apache.http]': OFF
        '[org.apache.hc.client5.http]': OFF

